#!/usr/bin/env python3
"""Generate per-tool instruction files from the canonical rules/ directory."""

import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).parent
RULES = ROOT / "rules"
DIST = ROOT / "dist"

# Documented caps: Codex concatenates AGENTS.md files with a 32 KiB ceiling;
# Windsurf allows 12 000 chars per rule file.
CODEX_CAP = 32 * 1024
WINDSURF_RULE_CAP = 12_000


def parse(path):
    text = path.read_text()
    match = re.match(r"^---\n(.*?)\n---\n+(.*)$", text, re.DOTALL)
    if not match:
        return [], text
    front, body = match.groups()
    globs = re.findall(r'-\s*"([^"]+)"', front)
    return globs, body


def write(path, content):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


def main():
    if DIST.exists():
        shutil.rmtree(DIST)

    rules = sorted(RULES.glob("*.md"))
    if not rules:
        sys.exit("no rules found")

    agents_parts = []

    for rule in rules:
        globs, body = parse(rule)
        stem = rule.stem
        scope = ", ".join(globs) if globs else "all files"

        # Claude Code: canonical format, copied unchanged.
        write(DIST / "claude/rules" / rule.name, rule.read_text())

        # Cursor: .mdc extension, globs/alwaysApply frontmatter.
        cursor_front = ["---", f"description: {stem}"]
        if globs:
            cursor_front += [f"globs: {','.join(globs)}", "alwaysApply: false"]
        else:
            cursor_front.append("alwaysApply: true")
        cursor_front.append("---")
        write(DIST / "cursor/rules" / f"{stem}.mdc", "\n".join(cursor_front) + "\n\n" + body)

        # GitHub Copilot: applyTo frontmatter, one glob string.
        apply_to = ",".join(globs) if globs else "**"
        write(
            DIST / "copilot/instructions" / f"{stem}.instructions.md",
            f'---\napplyTo: "{apply_to}"\n---\n\n{body}',
        )

        # Windsurf: trigger + globs frontmatter.
        if globs:
            ws_front = f"---\ntrigger: glob\nglobs: {','.join(globs)}\n---"
        else:
            ws_front = "---\ntrigger: always_on\n---"
        ws = f"{ws_front}\n\n{body}"
        if len(ws) > WINDSURF_RULE_CAP:
            print(f"  warning: {stem} is {len(ws)} chars, over Windsurf's 12000 cap")
        write(DIST / "windsurf/rules" / rule.name, ws)

        # Codex / opencode / Gemini: no path scoping — one concatenated file.
        agents_parts.append(f"# {stem}\n\nApplies to: {scope}\n\n{body}")

    agents = (
        "<!-- Generated by build.py — edit rules/ instead. -->\n\n"
        "# Agent Instructions\n\n" + "\n\n---\n\n".join(agents_parts)
    )
    write(DIST / "AGENTS.md", agents)

    size = len(agents.encode())
    print(f"generated dist/ from {len(rules)} rules")
    print(f"  AGENTS.md: {size} bytes", end="")
    print(f" — WARNING: over Codex's {CODEX_CAP}-byte cap" if size > CODEX_CAP else " (ok)")


if __name__ == "__main__":
    main()
